language: php

sudo: required

matrix:
  include:
    - php: 7.2
      env: SW_VERSION="4.5.10"
    - php: 7.3
      env: SW_VERSION="4.5.11"
    - php: 7.4
      env: SW_VERSION="4.6.0"

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash .travis/swoole.install.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add .travis/ci.ini
  - bash .travis/setup.mysql.sh
  - cp .travis/.env.example .env
  - cp phpunit.xml.dist phpunit.xml
  - travis_retry composer install --no-suggest --no-interaction

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer config -g process-timeout 900 && composer update -o

script:
  - composer test
